// Generated by scripts/contracts.py from the room-chat kit (chat@1). Do not edit.
// Regenerate with: python scripts/contracts.py build

export interface ChatAuthor {
  id: string;
  name?: string | null;
}

/** Recent history, sent to a connection when it joins. */
export interface ChatBacklogMessage {
  action: "chat_backlog";
  payload: ChatBacklogPayload;
}

export interface ChatBacklogPayload {
  room: string;
  entries: Array<ChatEntry>;
}

/** Client asks for history again, without reconnecting. */
export interface ChatBacklogRequestMessage {
  action: "chat_backlog_request";
  payload?: ChatBacklogRequestPayload;
}

export interface ChatBacklogRequestPayload {
  limit?: number | null;
}

/** One persisted chat message. */
export interface ChatEntry {
  body: string;
  author: ChatAuthor;
  room: string;
  id?: string;
  sent_at?: string;
}

/** A message published to the room. */
export interface ChatMessage {
  action: "chat_message";
  payload: ChatEntry;
}

/** Client posts a message to the room. */
export interface ChatSendMessage {
  action: "chat_send";
  payload: ChatSendPayload;
}

export interface ChatSendPayload {
  body: string;
}

/** What a client may send on a topic speaking this contract. */
export type ContractToServer = ChatBacklogRequestMessage | ChatSendMessage;
/** What such a topic sends to the client. */
export type ContractToClient = ChatBacklogMessage | ChatMessage;
