// Generated by scripts/contracts.py from the notification kit (notification@1). Do not edit.
// Regenerate with: python scripts/contracts.py build

/** Client acknowledges that notifications were seen. */
export interface NotificationAckMessage {
  action: "notification_ack";
  payload: NotificationAckPayload;
}

export interface NotificationAckPayload {
  ids: Array<string>;
}

/** Server confirms an acknowledgement was recorded. */
export interface NotificationAckedMessage {
  action: "notification_acked";
  payload: NotificationAckPayload;
}

export type NotificationLevel = "info" | "success" | "warning" | "error";

/** A notification delivered to the client. */
export interface NotificationMessage {
  action: "notification";
  payload: NotificationPayload;
}

export interface NotificationPayload {
  title: string;
  body?: string | null;
  level?: NotificationLevel;
  id?: string;
  created_at?: string;
  data?: Record<string, unknown>;
}

/** What a client may send on a topic speaking this contract. */
export type ContractToServer = NotificationAckMessage;
/** What such a topic sends to the client. */
export type ContractToClient = NotificationAckedMessage | NotificationMessage;
