// Generated by scripts/contracts.py from the audio-stream-in kit (transcriber@1). Do not edit.
// Regenerate with: python scripts/contracts.py build

/** ``index`` counts from 0 for each ``audio_start``, so a gap can be detected. */
export interface AudioChunk {
  index: number;
  data: string;
}

/** A piece of the stream. */
export interface AudioChunkMessage {
  action: "audio_chunk";
  payload: AudioChunk;
}

/** The format the server wants, and how much audio to put in each chunk. */
export interface AudioConfig {
  encoding: "pcm16";
  sample_rate?: number;
  channels?: number;
  chunk_ms?: number;
}

/** Sent on subscribe: capture to this format. */
export interface AudioConfigMessage {
  action: "audio_config";
  payload: AudioConfig;
}

/** Client asks for the capture format again, without resubscribing. */
export interface AudioConfigRequestMessage {
  action: "audio_config_request";
  payload?: null;
}

/** The stream is over: flush what the provider holds, then close it. */
export interface AudioEndMessage {
  action: "audio_end";
  payload?: null;
}

/** The format actually captured, which must match ``audio_config``. */
export interface AudioStart {
  encoding: "pcm16";
  sample_rate?: number;
  channels?: number;
  language?: string | null;
}

/** Client begins a stream of audio. */
export interface AudioStartMessage {
  action: "audio_start";
  payload: AudioStart;
}

export interface SpeechStarted {
  at_ms: number;
}

/** The provider heard speech begin, for barge-in and "listening" indicators. */
export interface SpeechStartedMessage {
  action: "speech_started";
  payload: SpeechStarted;
}

export interface TranscriberError {
  code: TranscriberErrorCode;
  message: string;
}

export type TranscriberErrorCode = "provider_unavailable" | "limit_reached" | "bad_format" | "audio_gap" | "not_started";

/** Something went wrong. Every code except ``audio_gap`` ends the stream. */
export interface TranscriberErrorMessage {
  action: "transcriber_error";
  payload: TranscriberError;
}

/** Times are milliseconds from the ``audio_start`` of this stream. */
export interface Transcript {
  utterance_id: string;
  text: string;
  start_ms: number;
  end_ms: number;
}

export interface TranscriptFinal {
  utterance_id: string;
  text: string;
  start_ms: number;
  end_ms: number;
  confidence?: number | null;
}

/** A segment that will not change. An utterance is its finals in order. */
export interface TranscriptFinalMessage {
  action: "transcript_final";
  payload: TranscriptFinal;
}

/** The segment being spoken, so far. Replaces the previous partial of the utterance. */
export interface TranscriptPartialMessage {
  action: "transcript_partial";
  payload: Transcript;
}

export interface UtteranceEnd {
  utterance_id: string;
}

/** The speaker paused: the utterance is complete. */
export interface UtteranceEndMessage {
  action: "utterance_end";
  payload: UtteranceEnd;
}

/** What a client may send on a topic speaking this contract. */
export type ContractToServer = AudioChunkMessage | AudioConfigRequestMessage | AudioEndMessage | AudioStartMessage;
/** What such a topic sends to the client. */
export type ContractToClient = AudioConfigMessage | SpeechStartedMessage | TranscriberErrorMessage | TranscriptFinalMessage | TranscriptPartialMessage | UtteranceEndMessage;
