# Generated by Django 6.0.7 on 2026-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatEntryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_id", models.CharField(max_length=32, unique=True)),
                ("room", models.CharField(max_length=255)),
                ("author_id", models.CharField(max_length=255)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "-sent_at"], name="django_mess_room_029a21_idx"
                    )
                ],
            },
        ),
    ]
