// Generated by scripts/contracts.py from the audio-stream-out kit (synthesizer@1). Do not edit.
// Regenerate with: python scripts/contracts.py build

/** How much of an utterance was actually heard, in milliseconds. */
export interface PlaybackMark {
  utterance_id: string;
  played_ms: number;
}

/** Client reports playback progress, so the server knows what was heard. */
export interface PlaybackMarkMessage {
  action: "playback_mark";
  payload: PlaybackMark;
}

export interface Speak {
  text: string;
  voice?: string | null;
  utterance_id?: string | null;
}

/** Client asks to stop: the utterance playing and everything queued. */
export interface SpeakClearMessage {
  action: "speak_clear";
  payload?: null;
}

/** Client asks for text to be spoken. Queued behind what is already speaking. */
export interface SpeakMessage {
  action: "speak";
  payload: Speak;
}

/** ``index`` counts from 0 per utterance, so a replayed chunk can be recognised. */
export interface SpeechAudioChunk {
  utterance_id: string;
  index: number;
  data: string;
}

/** A piece of the utterance's audio. */
export interface SpeechAudioChunkMessage {
  action: "audio_chunk";
  payload: SpeechAudioChunk;
}

export interface SpeechAudioEnd {
  utterance_id: string;
  duration_ms: number;
}

/** The utterance's audio is complete. */
export interface SpeechAudioEndMessage {
  action: "audio_end";
  payload: SpeechAudioEnd;
}

export interface SpeechAudioStart {
  encoding: "pcm16";
  sample_rate?: number;
  channels?: number;
  utterance_id: string;
  text: string;
}

/** An utterance begins, in this format. */
export interface SpeechAudioStartMessage {
  action: "audio_start";
  payload: SpeechAudioStart;
}

/** The utterance that was playing, if any. */
export interface SpeechClear {
  utterance_id?: string | null;
}

/** Stop playing now and drop anything buffered: an interruption. */
export interface SpeechClearMessage {
  action: "clear";
  payload: SpeechClear;
}

export interface SynthesizerError {
  code: SynthesizerErrorCode;
  message: string;
  utterance_id?: string | null;
}

export type SynthesizerErrorCode = "provider_unavailable" | "bad_request" | "provider_failed";

/** An utterance could not be spoken. */
export interface SynthesizerErrorMessage {
  action: "synthesizer_error";
  payload: SynthesizerError;
}

/** What a client may send on a topic speaking this contract. */
export type ContractToServer = PlaybackMarkMessage | SpeakClearMessage | SpeakMessage;
/** What such a topic sends to the client. */
export type ContractToClient = SpeechAudioChunkMessage | SpeechAudioEndMessage | SpeechAudioStartMessage | SpeechClearMessage | SynthesizerErrorMessage;
