// Generated by scripts/contracts.py from the presence kit (presence@1). Do not edit.
// Regenerate with: python scripts/contracts.py build

export interface PresenceEventPayload {
  scope: string;
  member: PresenceMember;
}

/** Someone became present in the scope. */
export interface PresenceJoinMessage {
  action: "presence_join";
  payload: PresenceEventPayload;
}

/** Someone is no longer present in the scope. */
export interface PresenceLeaveMessage {
  action: "presence_leave";
  payload: PresenceEventPayload;
}

/** Someone present in a scope. ``id`` is what identifies them across connections. */
export interface PresenceMember {
  id: string;
  name?: string | null;
  data?: Record<string, unknown>;
}

/** Client asks for the roster again, without reconnecting. */
export interface PresenceRequestMessage {
  action: "presence_request";
  payload?: null;
}

/** Full member list, sent to a connection when it joins. */
export interface PresenceStateMessage {
  action: "presence_state";
  payload: PresenceStatePayload;
}

export interface PresenceStatePayload {
  scope: string;
  members: Array<PresenceMember>;
}

/** What a client may send on a topic speaking this contract. */
export type ContractToServer = PresenceRequestMessage;
/** What such a topic sends to the client. */
export type ContractToClient = PresenceJoinMessage | PresenceLeaveMessage | PresenceStateMessage;
