#!/usr/bin/env python
"""Generate each UI kit's ``contract.ts`` with the codegen apps use.

python scripts/contracts.py build|check    # needs the fastapi extra and npm ci --prefix ui
"""

import argparse
import importlib
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, ClassVar

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
UI_ROOT = REPO_ROOT / "ui"
CODEGEN = UI_ROOT / "node_modules" / ".bin" / "chanx-codegen"

HEADER = """\
// Generated by scripts/contracts.py from the {kit} kit ({contract}). Do not edit.
// Regenerate with: python scripts/contracts.py build
"""


def load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text()) or {}


def defined_contracts() -> dict[str, tuple[str, str]]:
    """``name@version`` -> (kit directory, contract topic class)."""
    found: dict[str, tuple[str, str]] = {}
    for manifest in sorted((REPO_ROOT / "kits").glob("*/kit.yaml")):
        data = load_yaml(manifest)
        if data.get("defines"):
            found[str(data["defines"])] = (
                manifest.parent.name,
                str(data["contract_topic"]),
            )
    return found


def consumers() -> dict[Path, str]:
    """UI kit directory -> the contract its ``contract.ts`` carries."""
    found: dict[Path, str] = {}
    for manifest in sorted(UI_ROOT.glob("*/kit.yaml")):
        consumes = load_yaml(manifest).get("consumes") or []
        if consumes:
            found[manifest.parent] = str(consumes[0])
    return found


def asyncapi_for(kit: str, topic_name: str) -> str:
    """The AsyncAPI document of an app listing only the contract topic."""
    from chanx.core.decorators import channel
    from chanx.core.topic import Topic
    from chanx.fast_channels import asyncapi_spec_json
    from chanx.fast_channels.type_defs import AsyncAPIConfig
    from chanx.fast_channels.websocket import AsyncJsonWebsocketConsumer
    from fastapi import FastAPI
    from fastapi.requests import Request
    from fastapi.responses import JSONResponse
    from fastapi.testclient import TestClient

    base = getattr(importlib.import_module(f"kits.{kit}"), topic_name)
    # Same name as the base, so nothing kit-specific leaks into the generated names.
    contract_topic = type(topic_name, (base,), {"pattern": "contract"})

    @channel(name="contract")
    class ContractConsumer(AsyncJsonWebsocketConsumer[Any]):
        topics: ClassVar[list[type[Topic[Any]]]] = [contract_topic]

    app = FastAPI()
    ws = FastAPI()
    ws.router.add_websocket_route("/contract", ContractConsumer.as_asgi())
    app.mount("/ws", ws)

    @app.get("/asyncapi.json")
    async def spec(request: Request) -> JSONResponse:
        return await asyncapi_spec_json(
            request=request, app=app, config=AsyncAPIConfig(version="1")
        )

    return TestClient(app).get("/asyncapi.json").text


UNION = re.compile(r"^export type Contract\w+?(ToServer|ToClient) = (.+);$", re.M)


def render(kit: str, contract: str, topic_name: str) -> str:
    if not CODEGEN.exists():
        raise SystemExit(f"{CODEGEN} is missing. Run: npm ci --prefix ui")

    with tempfile.TemporaryDirectory() as tmp:
        spec = Path(tmp) / "asyncapi.json"
        # One process per contract: chanx registers consumers globally.
        spec.write_text(
            subprocess.run(
                [sys.executable, __file__, "spec", kit, topic_name],
                check=True,
                capture_output=True,
                text=True,
            ).stdout
        )
        out = Path(tmp) / "generated"
        subprocess.run(
            [str(CODEGEN), str(spec), "-o", str(out)],
            check=True,
            capture_output=True,
        )
        schemas = (out / "schemas.ts").read_text()
        channels = (out / "channels.ts").read_text()

    unions = dict(UNION.findall(channels))
    body = schemas.split("\n", 3)[3].lstrip("\n")  # drop codegen's own header
    return (
        HEADER.format(kit=kit.replace("_", "-"), contract=contract)
        + "\n"
        + body.rstrip("\n")
        + "\n\n/** What a client may send on a topic speaking this contract. */\n"
        + f"export type ContractToServer = {unions.get('ToServer', 'never')};\n"
        + "/** What such a topic sends to the client. */\n"
        + f"export type ContractToClient = {unions.get('ToClient', 'never')};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["build", "check", "spec"])
    parser.add_argument("spec_args", nargs="*", help=argparse.SUPPRESS)
    args = parser.parse_args()

    sys.path.insert(0, str(REPO_ROOT))
    if args.command == "spec":
        print(asyncapi_for(*args.spec_args))
        return 0
    defined = defined_contracts()
    stale: list[str] = []

    for directory, contract in consumers().items():
        if contract not in defined:
            print(f"{directory.name}: consumes undefined {contract}", file=sys.stderr)
            return 1
        kit, topic_name = defined[contract]
        rendered = render(kit, contract, topic_name)
        target = directory / "contract.ts"
        if args.command == "build":
            target.write_text(rendered)
            print(f"Wrote {target.relative_to(REPO_ROOT)} ({contract})")
        elif not target.exists() or target.read_text() != rendered:
            stale.append(str(target.relative_to(REPO_ROOT)))

    if stale:
        print(
            "Stale contracts: " + ", ".join(stale) + ". "
            "Run: python scripts/contracts.py build",
            file=sys.stderr,
        )
        return 1
    if args.command == "check":
        print("Contracts OK.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
