#!/usr/bin/env python
"""Generate TypeScript types from a chanx AsyncAPI 3.0 spec: discriminated-union
types per channel, checked against the same contract the server generates.

    python scripts/gen_ts_client.py --app sandbox.main:app -o sandbox/ui/src/generated
    python scripts/gen_ts_client.py --url http://localhost:8000/asyncapi.json -o ...

Emits schemas.ts (payloads and messages), channels.ts (per-channel unions), index.ts.
"""

from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
from pathlib import Path
from typing import Any

HEADER = (
    "// Generated by scripts/gen_ts_client.py — do not edit.\n"
    "// Regenerate with: pnpm gen\n\n"
)

_SCALARS = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def load_spec(app_path: str | None, url: str | None) -> dict[str, Any]:
    if url:
        import urllib.request

        with urllib.request.urlopen(url) as response:  # noqa: S310
            return json.load(response)

    if not app_path:
        raise SystemExit("Pass --app module:attr or --url")

    module_name, _, attr = app_path.partition(":")
    sys.path.insert(0, str(Path.cwd()))
    module = importlib.import_module(module_name)
    app = getattr(module, attr or "app")

    from fastapi.testclient import TestClient

    response = TestClient(app).get("/asyncapi.json")
    response.raise_for_status()
    return json.loads(response.text)


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def ts_type(schema: dict[str, Any], indent: int = 0) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])

    if "const" in schema:
        return json.dumps(schema["const"])

    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])

    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " | ".join(ts_type(option, indent) for option in schema[key])

    if "allOf" in schema and len(schema["allOf"]) == 1:
        return ts_type(schema["allOf"][0], indent)

    schema_type = schema.get("type")

    if isinstance(schema_type, list):
        return " | ".join(_SCALARS.get(item, "unknown") for item in schema_type)

    if schema_type == "array":
        item = ts_type(schema.get("items", {}), indent)
        # An array of a union needs parentheses: (A | B)[]
        return f"({item})[]" if " | " in item else f"{item}[]"

    if schema_type == "object" or "properties" in schema:
        if "properties" not in schema:
            extra = schema.get("additionalProperties")
            value = ts_type(extra, indent) if isinstance(extra, dict) else "unknown"
            return f"Record<string, {value}>"
        return render_object(schema, indent)

    if schema_type in _SCALARS:
        return _SCALARS[schema_type]

    return "unknown"


def render_object(schema: dict[str, Any], indent: int) -> str:
    pad = "  " * (indent + 1)
    closing = "  " * indent
    required = set(schema.get("required", []))
    lines: list[str] = ["{"]

    for name, prop in schema.get("properties", {}).items():
        # Const fields (the `action` discriminator) are always on the wire but not in
        # `required`; emitting them optional would break TS union narrowing.
        always_present = name in required or "const" in prop
        optional = "" if always_present else "?"
        doc = prop.get("description")
        if doc:
            lines.append(f"{pad}/** {' '.join(doc.split())} */")
        lines.append(f"{pad}{json_key(name)}{optional}: {ts_type(prop, indent + 1)};")

    lines.append(f"{closing}}}")
    return "\n".join(lines)


_SAFE_KEY = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def json_key(name: str) -> str:
    return name if _SAFE_KEY.match(name) else json.dumps(name)


def render_schemas(spec: dict[str, Any]) -> str:
    schemas: dict[str, Any] = spec.get("components", {}).get("schemas", {})
    chunks: list[str] = [HEADER]

    for name in sorted(schemas):
        schema = schemas[name]
        description = schema.get("description")
        if description:
            chunks.append(f"/** {' '.join(description.split())} */\n")
        if "properties" in schema or schema.get("type") == "object":
            chunks.append(f"export interface {name} {render_object(schema, 0)}\n\n")
        else:
            chunks.append(f"export type {name} = {ts_type(schema)};\n\n")

    return "".join(chunks)


def message_schema_name(spec: dict[str, Any], message_ref: str) -> str | None:
    key = ref_name(message_ref)
    message = spec.get("components", {}).get("messages", {}).get(key)
    if not message:
        return None
    payload = message.get("payload", {})
    if "$ref" in payload:
        return ref_name(payload["$ref"])
    return None


def channel_messages(spec: dict[str, Any]) -> dict[str, dict[str, set[str]]]:
    """Split each channel's messages by direction, named from the client's point of
    view (AsyncAPI's ``receive``/``send`` are the server's)."""
    directions: dict[str, dict[str, set[str]]] = {
        name: {"toServer": set(), "toClient": set()}
        for name in spec.get("channels", {})
    }

    for operation in spec.get("operations", {}).values():
        channel = ref_name(operation.get("channel", {}).get("$ref", ""))
        if channel not in directions:
            continue

        outbound = operation.get("action") == "send"
        bucket = "toClient" if outbound else "toServer"

        for message in operation.get("messages", []):
            name = message_schema_name(spec, message.get("$ref", ""))
            if name:
                directions[channel][bucket].add(name)

        reply = operation.get("reply") or {}
        for message in reply.get("messages", []):
            name = message_schema_name(spec, message.get("$ref", ""))
            if name:
                directions[channel]["toClient"].add(name)

    return directions


def pascal(value: str) -> str:
    return "".join(part.title() for part in re.split(r"[^A-Za-z0-9]+", value) if part)


def render_channels(spec: dict[str, Any]) -> str:
    channels: dict[str, Any] = spec.get("channels", {})
    directions = channel_messages(spec)

    names = sorted(
        {
            name
            for channel in directions.values()
            for bucket in channel.values()
            for name in bucket
        }
    )

    chunks: list[str] = [HEADER]
    if names:
        imported = ",\n  ".join(names)
        chunks.append(f"import type {{\n  {imported},\n}} from './schemas';\n\n")

    for channel_name in sorted(channels):
        channel = channels[channel_name]
        prefix = pascal(channel_name)
        to_server = sorted(directions[channel_name]["toServer"]) or ["never"]
        to_client = sorted(directions[channel_name]["toClient"]) or ["never"]

        description = channel.get("description")
        if description:
            chunks.append(f"/** {' '.join(description.split())} */\n")
        chunks.append(
            f"export const {prefix}Address = {json.dumps(channel.get('address', ''))} as const;\n"
        )
        chunks.append(
            f"export type {prefix}ToServer = {' | '.join(to_server)};\n"
            f"export type {prefix}ToClient = {' | '.join(to_client)};\n"
            f"export interface {prefix}Channel {{\n"
            f"  toServer: {prefix}ToServer;\n"
            f"  toClient: {prefix}ToClient;\n"
            f"}}\n\n"
        )

    registry = ",\n".join(
        f"  {json_key(name)}: {pascal(name)}Channel" for name in sorted(channels)
    )
    chunks.append(f"export interface Channels {{\n{registry}\n}}\n")
    return "".join(chunks)


def write(path: Path, content: str) -> None:
    # Exactly one trailing newline, or the end-of-file-fixer hook and regeneration
    # would fight and CI's `git diff --exit-code` would never settle.
    path.write_text(content.rstrip("\n") + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app", help="ASGI app as module:attr, e.g. sandbox.main:app")
    parser.add_argument("--url", help="URL of an asyncapi.json document")
    parser.add_argument("-o", "--out", required=True, help="Output directory")
    args = parser.parse_args()

    spec = load_spec(args.app, args.url)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    write(out / "schemas.ts", render_schemas(spec))
    write(out / "channels.ts", render_channels(spec))
    write(
        out / "index.ts",
        HEADER + "export * from './schemas';\nexport * from './channels';",
    )

    schema_count = len(spec.get("components", {}).get("schemas", {}))
    print(
        f"Generated {schema_count} types across "
        f"{len(spec.get('channels', {}))} channels into {out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
